# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-14 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalyan', '0015_auto_20170818_0225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applications',
            options={'ordering': ['created_on'], 'verbose_name': 'Application', 'verbose_name_plural': 'Applications'},
        ),
        migrations.AlterField(
            model_name='applications',
            name='app_name',
            field=models.CharField(default='application', max_length=50, verbose_name='Application Name'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='uname',
            field=models.CharField(max_length=50, verbose_name='User name'),
        ),
    ]
